---
- name: Configure description on Ethernet1
  hosts: Leaf1
  gather_facts: false
  tasks:
    - name: Configure description on Ethernet1
      eos_config:
        lines:
        - description TEST-Lab01
        parents: interface ethernet1

    - name: Get switch Ethernet1 interface configuration
      eos_command:
        commands: "show run interface Ethernet1"
      register: ethernet1

    - name: Print Ethernet1 new configuration
      debug:
        msg: " {{ ethernet1.stdout_lines }} "